### ISSUE TITLE
scroll deployment fails

### ISSUE THREAD

**Issue by hrishikeshio** [razor-network/bridge-proxy#86]
npx hardhat run scripts/deployBridge.js --network scroll
Validating block timestamp of the deploying chain
Deployer address: 0xB32A48c1FC59A9954617D8B22c72f509E985a852
Oracle Chain Latest Block Timestamp: 1709200910
Deploying Chain Latest Block Timestamp: 1709200923
Time difference (Deploying Chain - Native Chain) in seconds: 13
Success: The time difference is within ±15 seconds.
Finished checking time difference.
Current gasPrice: 432000000
20% Higher used gasPrice 518400000
Gas Price used 518400000 wei
Deploying ResultManager contract...
√ [hardhat-ledger] Connecting wallet
√ [hardhat-ledger] Waiting for confirmation
ProviderError: transaction type not supported
    at HttpProvider.request (C:\Users\Hrishikesh\razor\bridge-proxy\node_modules\hardhat\src\internal\core\providers\http.ts:88:21)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at LedgerProvider.request (C:\Users\Hrishikesh\razor\bridge-proxy\node_modules\@nomicfoundation\hardhat-ledger\src\provider.ts:137:18)
    at EthersProviderWrapper.send (C:\Users\Hrishikesh\razor\bridge-proxy\node_modules\@nomiclabs\hardhat-ethers\src\internal\ethers-provider-wrapper.ts:13:20)

**Comment by hrishikeshio** [comment]
maybe because eip 1559 is not supported.
was is tested on scroll testnet?

https://docs.scroll.io/en/technology/chain/transactions/

**Comment by yohanelly95** [comment]
> maybe because eip 1559 is not supported. was is tested on scroll testnet?
> 
> https://docs.scroll.io/en/technology/chain/transactions/

@hrishikeshio yes the same script was used for testnet deployments. We can try running it with the forge deployment script which will be merged soon.
